[workspace]
authors = ["Richard Johnsson <Richard.Johnsson@hotmail.se>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojoreq"
platforms = ["osx-arm64", "linux-64"]
version = "0.2.0"

[tasks]
test = "mojo run -I src tests/requests_test.mojo"
test-integration = "tests/run_local_integration.sh"
test-integration-live = "MOJOREQ_RUN_INTEGRATION_LIVE=1 mojo run -I src tests/integration_live_test.mojo"
test-live = "MOJOREQ_RUN_INTEGRATION_LIVE=1 mojo run -I src tests/integration_live_test.mojo"

[dependencies]
mojo = ">=0.26.2.0.dev2026030205,<0.27"
